### ISSUE TITLE
The UI seems to crash before the Database is ready

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/echo#105]
When launching the App locally or in the Cloud. When the DB isn't ready, it seems the UI fails on parsing the results.

```
    at qm (MobileDemo.tsx:23:58)
    at ua (react-dom.production.min.js:157:137)
    at La (react-dom.production.min.js:180:154)
    at Ju (react-dom.production.min.js:269:343)
    at Os (react-dom.production.min.js:250:347)
    at Ts (react-dom.production.min.js:250:278)
    at Cs (react-dom.production.min.js:250:138)
    at xs (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
```

**Comment by alecmerdler** [comment]
This has been fixed.
